version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.6-slim-stretch
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run:
        name: Install package
      - run: apt-get update
      - run: apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev libyaml-dev libcurl4-openssl-dev libffi-dev pkg-config
      - run: apt-get install -y apache2 apache2-dev libapr1-dev libaprutil1-dev
      - run: apt-get install -y imagemagick libmagick++-dev
      - run: apt-get install -y cvs mercurial subversion git bzr










