version: 2.1
jobs:
  build:
    docker:
      - image: ruby:2.6-slim-stretch
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev libyaml-dev libcurl4-openssl-dev libffi-dev pkg-config
      - run: apt-get install -y apache2 apache2-dev libapr1-dev libaprutil1-dev
      - run: apt-get install -y imagemagick libmagick++-dev
      - run: apt-get install -y cvs mercurial subversion git bzr
      - run: apt-get install -y debconf-utils tzdata wget
      - run: echo 'mysql-server mysql-server/root_password password redmine' | debconf-set-selections
      - run: echo 'mysql-server mysql-server/root_password_again password redmine' | debconf-set-selections
      - run: wget https://dev.mysql.com/get/mysql-apt-config_0.8.9-1_all.deb
      - run: apt install -y ./mysql-apt-config_0.8.9-1_all.deb
      - run: apt-get update
      - run: apt-get install -y --allow-unauthenticated mysql-community-server default-libmysqlclient-dev
      - run: /etc/init.d/mysql start
      - run: mysql -u root -predmine -e "CREATE DATABASE redmine CHARACTER SET utf8mb4;"
 







